# *** GENERATED BY easyMathSolver, DO NOT EDIT BY HAND ***
#
# Generated from custom LaTeX.g4 (modified from SymPy's version)
#     Original latex2sympy is licensed under the MIT license
#     https://github.com/augustt198/latex2sympy/blob/master/LICENSE.txt
#
# Generated with antlr4
#    antlr4 is licensed under the BSD-3-Clause License
#    https://github.com/antlr/antlr4/blob/master/LICENSE.txt
